apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-fetcher
  namespace: weather-logger
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: weather-fetcher
              image: kitancodes/weather-logger:v1
              env:
                - name: OPENWEATHER_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: weather-secret
                      key: OPENWEATHER_API_KEY
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: weather-secret
                      key: DB_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-secret
                      key: DB_PASSWORD
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: weather-secret
                      key: DB_NAME
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: DB_HOST
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: DB_PORT
                - name: CITIES
                  valueFrom:
                    configMapKeyRef:
                      name: app-config
                      key: CITIES
          restartPolicy: OnFailure
