apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
  namespace: weather-logger
type: Opaque
data:
  DB_USER: d2VhdGhlcnVzZXI=
  DB_PASSWORD: d2VhdGhlcnBhc3N3b3Jk
  DB_NAME: d2VhdGhlcmRi
  OPENWEATHER_API_KEY: OGNiYjcwMjg4OGViMTlkYzc3YzUzMmZhMGJhYjk3ODc=
