apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
  namespace: weather-logger
type: Opaque
data:
  DB_USER: <base64-encoded-db-user>
  DB_PASSWORD: <base64-encoded-db-password>
  DB_NAME: <base64-encoded-db-name>
  OPENWEATHER_API_KEY: <base64-encoded-api-key>
